name: nimisar_tourism
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  dart_openai: ^5.0.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  readmore: ^2.2.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
